kind: pipeline
type: docker
name: liquibase-pipeline

steps:
  - name: liquibase-update
    image: liquibase/liquibase:latest
    environment:
      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/mydb
      LIQUIBASE_USERNAME: user
      LIQUIBASE_PASSWORD: password
    commands:
      - liquibase --changeLogFile=/liquibase/changelog/db.changelog-master.xml update
